name: Documentation Bug
description: Identify a flaw or ambiguity in the documentation
title: "[doc-bug]: "
labels: ["doc-bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!
  - type: textarea
    id: file
    attributes:
      label: File
      description: Identify the file where there is a problem
      placeholder: README.md
    validations:
      required: true
  - type: textarea
    id: doc-issue
    attributes:
      label: Documentation Issue
      description: Identify the short coming
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Other
